import { Author, Post, Tag, WorkPhoto } from "./types";
import { getImage } from "./local-images";

const authors: Record<string, Author> = {
  a1: { id: "a1", name: "Tanaka Ryō",       avatarUrl: "https://picsum.photos/seed/author-jp1/64/64", country: "JP", bio: "10+ years building Gunpla. Specializes in weathering and LED integration. Tokyo-based modeler.", followersCount: 1240, followingCount: 89 },
  a2: { id: "a2", name: "Chen Wei-Ting",    avatarUrl: "https://picsum.photos/seed/author-tw1/64/64", country: "TW", bio: "台湾のガンプラビルダー。キャンディ塗装とバトルダメージが得意です。", followersCount: 867, followingCount: 134 },
  a3: { id: "a3", name: "Park Ji-Hoon",     avatarUrl: "https://picsum.photos/seed/author-kr1/64/64", country: "KR", bio: "PG specialist from Seoul. Scribing and precision painting are my passion.", followersCount: 2100, followingCount: 56 },
  a4: { id: "a4", name: "Marcus Webb",      avatarUrl: "https://picsum.photos/seed/author-us1/64/64", country: "US", bio: "Diorama builder from Portland, OR. I create mini worlds around every build.", followersCount: 1580, followingCount: 210 },
  a5: { id: "a5", name: "Yamamoto Keisuke", avatarUrl: "https://picsum.photos/seed/author-jp2/64/64", country: "JP", bio: "PG/MG builder focused on LED integration. Based in Osaka.", followersCount: 3200, followingCount: 88 },
  a6: { id: "a6", name: "Thomas Müller",    avatarUrl: "https://picsum.photos/seed/author-de1/64/64", country: "DE", bio: "Military scale modeler from Munich. 1/35 AFV specialist with 15 years experience.", followersCount: 456, followingCount: 67 },
  a7: { id: "a7", name: "Sophie Laurent",   avatarUrl: "https://picsum.photos/seed/author-fr1/64/64", country: "FR", bio: "Aviation modeler from Lyon. 1/48 WWII aircraft with natural metal finish.", followersCount: 320, followingCount: 45 },
  a8: { id: "a8", name: "Hiroshi Yamada",   avatarUrl: "https://picsum.photos/seed/author-jp3/64/64", country: "JP", bio: "Car model enthusiast from Nagoya. Tamiya 1/24 with extreme interior detail.", followersCount: 290, followingCount: 38 },
};

function lp(category: Parameters<typeof getImage>[0], idx: number, caption: string): WorkPhoto {
  return { url: getImage(category, idx), caption };
}

export const posts: Post[] = [
  {
    id: "1", title: "MG Nu Gundam Ver.Ka — Full Psycho-Frame Weathering",
    description: "Heavy weathering on the iconic Ver.Ka with custom psycho-frame LED integration. Panel Line Accent Color and Tamiya weathering sticks for battlefield realism.",
    thumbnailUrl: getImage("Gunpla", 0),
    images: [
      lp("Gunpla", 0, "Front — full pose"),
      lp("Gunpla", 1, "Rear — backpack detail"),
      lp("Gunpla", 2, "Psycho-frame closeup"),
      lp("Gunpla", 3, "Weapons loadout"),
      lp("Gunpla", 4, "Weathering detail"),
    ],
    author: authors.a1, category: "Gunpla", tags: ["Weathering", "LED", "Scribing"],
    kit: "MG νGundam Ver.Ka", paints: ["Gaia Notes Ex White", "Mr.Color GX Metal Blue", "Tamiya Panel Line"],
    tools: ["GodHand Nipper", "BMC Chisel", "Tamiya Cement"],
    techniques: ["Weathering", "Scribing", "LED Integration"],
    saveCount: 342, likeCount: 289, weeklyLikeCount: 78, createdAt: "2026-05-10T09:00:00Z",
  },
  {
    id: "2", title: "HG Zaku II — Candy Red Battle Damage Build",
    description: "Experimental candy paint over chrome base with dramatic battle damage. Every dent and burn mark is hand-crafted with heat tools and scribing.",
    thumbnailUrl: getImage("Gunpla", 1),
    images: [
      lp("Gunpla", 1, "Front"),
      lp("Gunpla", 2, "Left flank — battle damage"),
      lp("Gunpla", 3, "Leg detail"),
      lp("Gunpla", 4, "Shoulder armor"),
    ],
    author: authors.a2, category: "Gunpla", tags: ["Candy Paint", "Battle Damage", "Weathering"],
    kit: "HG Zaku II", paints: ["Gaianotes Bright Red", "Alclad Chrome", "Mr.Color Clear Red"],
    tools: ["Airbrush", "Heat Gun", "BMC Chisel"],
    techniques: ["Candy Paint", "Battle Damage", "Chipping"],
    saveCount: 278, likeCount: 241, weeklyLikeCount: 65, createdAt: "2026-05-15T14:30:00Z",
  },
  {
    id: "3", title: "PG Strike Freedom — Snow White Premium Finish",
    description: "Perfect Grade with premium pearl white and gold accents. Extensive panel scribing and detail-up parts throughout.",
    thumbnailUrl: getImage("Gunpla", 2),
    images: [
      lp("Gunpla", 2, "Front — full wingspan"),
      lp("Gunpla", 3, "Rear — wings spread"),
      lp("Gunpla", 4, "Face closeup"),
      lp("Gunpla", 0, "Dragoons deployed"),
    ],
    author: authors.a3, category: "Gunpla", tags: ["Scribing", "LED"],
    kit: "PG Strike Freedom Gundam", paints: ["Mr.Color Super White", "Gaianotes Star Bright Gold", "Mr.Color GX Clear"],
    tools: ["GodHand Nipper", "BMC Chisel", "Tamiya Sanding Sponge"],
    techniques: ["Scribing", "LED Integration", "Panel Lining"],
    saveCount: 512, likeCount: 430, weeklyLikeCount: 55, createdAt: "2026-04-28T11:00:00Z",
  },
  {
    id: "4", title: "RG Evangelion Unit-01 — Battle Damage Diorama",
    description: "Full diorama depicting Unit-01's first battle. Handmade rubble, custom lighting, and extensive paint chipping.",
    thumbnailUrl: getImage("Character Model", 0),
    images: [
      lp("Character Model", 0, "Diorama — front view"),
      lp("Character Model", 1, "Rubble base detail"),
      lp("Character Model", 2, "Head closeup — damaged"),
      lp("Character Model", 3, "Night lighting shot"),
    ],
    author: authors.a4, category: "Character Model", tags: ["Diorama", "Battle Damage", "Weathering"],
    kit: "RG Evangelion Unit-01", paints: ["Tamiya XF-14 J.A Green", "Mr.Color Purple", "AK Interactive Rust"],
    tools: ["Airbrush", "Sculpting Tools", "LED Wiring Kit"],
    techniques: ["Diorama", "Battle Damage", "Chipping"],
    saveCount: 634, likeCount: 581, weeklyLikeCount: 52, createdAt: "2026-04-20T08:00:00Z",
  },
  {
    id: "5", title: "MG Sinanju — Dark Chrome Titanium Finish",
    description: "Sinanju in dark titanium chrome with custom decals. Titanium finish achieved with Alclad II lacquers over polished surface.",
    thumbnailUrl: getImage("Gunpla", 3),
    images: [
      lp("Gunpla", 3, "Front"),
      lp("Gunpla", 4, "Rear — thruster detail"),
      lp("Gunpla", 0, "Chrome reflection"),
    ],
    author: authors.a1, category: "Gunpla", tags: ["Candy Paint", "Scribing"],
    kit: "MG Sinanju Ver.Ka", paints: ["Alclad Titanium", "Alclad Chrome", "Mr.Color Red"],
    tools: ["Airbrush", "BMC Chisel", "Polishing Cloth"],
    techniques: ["Chrome Finish", "Scribing", "Decaling"],
    saveCount: 198, likeCount: 176, weeklyLikeCount: 44, createdAt: "2026-05-18T16:00:00Z",
  },
  {
    id: "6", title: "HG Barbatos — Desert Weathering Scene",
    description: "Barbatos placed in a desert diorama. Sand, rust, and oil streaks bring out the harsh conditions of Mars.",
    thumbnailUrl: getImage("Diorama", 0),
    images: [
      lp("Diorama", 0, "Diorama overview"),
      lp("Diorama", 1, "Sand and rust detail"),
      lp("Diorama", 2, "Low angle"),
    ],
    author: authors.a2, category: "Diorama", tags: ["Weathering", "Diorama"],
    kit: "HG Gundam Barbatos", paints: ["Tamiya Desert Yellow", "AK Interactive Sand", "Vallejo Rust"],
    tools: ["Airbrush", "Sponge", "Pigment Brushes"],
    techniques: ["Weathering", "Diorama", "Oil Wash"],
    saveCount: 156, likeCount: 143, weeklyLikeCount: 91, createdAt: "2026-05-20T10:00:00Z",
  },
  {
    id: "7", title: "RG RX-78-2 — Classic Tricolor Gloss Finish",
    description: "The original Gundam treated with high-gloss tricolor finish and gold foil stickers. Clean build emphasizing the classic design.",
    thumbnailUrl: getImage("Gunpla", 4),
    images: [
      lp("Gunpla", 4, "Front — action pose"),
      lp("Gunpla", 0, "Rear"),
      lp("Gunpla", 1, "With beam rifle"),
    ],
    author: authors.a5, category: "Gunpla", tags: ["Scribing"],
    kit: "RG RX-78-2 Gundam", paints: ["Mr.Color Gloss White", "Mr.Color Red", "Mr.Color Blue"],
    tools: ["GodHand Nipper", "Tweezers", "Mr.Mark Setter"],
    techniques: ["Gloss Finish", "Decaling", "Panel Lining"],
    saveCount: 89, likeCount: 74, weeklyLikeCount: 38, createdAt: "2026-05-22T09:30:00Z",
  },
  {
    id: "8", title: "MG Wing Zero EW — Crystal LED Diorama",
    description: "Wing Zero EW mounted mid-flight in a crystal diorama with internal LED glow. Wings fully spread with feather detail-up parts.",
    thumbnailUrl: getImage("Diorama", 1),
    images: [
      lp("Diorama", 1, "Wings spread — front"),
      lp("Diorama", 2, "Crystal base LED on"),
      lp("Diorama", 3, "Wing feather detail"),
      lp("Diorama", 4, "LED comparison dark"),
    ],
    author: authors.a4, category: "Diorama", tags: ["LED", "Diorama"],
    kit: "MG Wing Gundam Zero EW", paints: ["Mr.Color Super White", "Gaianotes Star Bright Gold", "Mr.Color GX Crystal Clear"],
    tools: ["LED Kit", "Resin Casting Tools", "GodHand Nipper"],
    techniques: ["LED Integration", "Diorama", "Resin Casting"],
    saveCount: 421, likeCount: 388, weeklyLikeCount: 48, createdAt: "2026-04-15T12:00:00Z",
  },
  {
    id: "9", title: "HG Sazabi — Deep Red Gloss with Gold Trim",
    description: "Sazabi in deep gloss red with hand-painted 24k gold trim. Each vent and thruster individually painted for maximum visual impact.",
    thumbnailUrl: getImage("Gunpla", 0),
    images: [
      lp("Gunpla", 0, "Front"),
      lp("Gunpla", 1, "Gold trim closeup"),
      lp("Gunpla", 2, "Thruster detail"),
    ],
    author: authors.a3, category: "Gunpla", tags: ["Candy Paint"],
    kit: "HG Sazabi", paints: ["Mr.Color GX Deep Red", "Gaianotes Star Bright Gold", "Mr.Color GX Super Clear III"],
    tools: ["Airbrush", "Fine Detail Brush", "Panel Liner"],
    techniques: ["Gloss Finish", "Hand Painting", "Panel Lining"],
    saveCount: 67, likeCount: 58, weeklyLikeCount: 29, createdAt: "2026-05-25T15:00:00Z",
  },
  {
    id: "10", title: "PG Unicorn — Full LED Psycho-Frame Reveal",
    description: "Perfect Grade Unicorn with complete custom LED setup. Both Unicorn and Destroy mode parts painted and lighting transitions perfected.",
    thumbnailUrl: getImage("Gunpla", 1),
    images: [
      lp("Gunpla", 1, "Unicorn mode — front"),
      lp("Gunpla", 2, "Destroy mode — LED on"),
      lp("Gunpla", 3, "Psycho-frame glow"),
      lp("Gunpla", 4, "Head closeup — glowing"),
      lp("Gunpla", 0, "Full pose in dark room"),
    ],
    author: authors.a5, category: "Gunpla", tags: ["LED", "Scribing", "Weathering"],
    kit: "PG Unicorn Gundam", paints: ["Mr.Color Super White", "Mr.Color Fluorescent Pink", "Tamiya Panel Line"],
    tools: ["Custom LED Kit", "BMC Chisel", "GodHand Nipper"],
    techniques: ["LED Integration", "Scribing", "Panel Lining"],
    saveCount: 789, likeCount: 712, weeklyLikeCount: 134, createdAt: "2026-03-30T10:00:00Z",
  },
  {
    id: "11", title: "RG Crossbone X1 — Space Pirate Diorama",
    description: "Crossbone Gundam X1 in a handcrafted space debris diorama. Skull motifs hand-painted and battle damage carved with dremel tools.",
    thumbnailUrl: getImage("Diorama", 2),
    images: [
      lp("Diorama", 2, "Diorama full shot"),
      lp("Diorama", 3, "Space debris base"),
      lp("Diorama", 4, "Skull motif closeup"),
    ],
    author: authors.a2, category: "Diorama", tags: ["Diorama", "Battle Damage", "Scribing"],
    kit: "RG Crossbone Gundam X1", paints: ["Mr.Color White", "Mr.Color Flat Black", "AK Interactive Silver"],
    tools: ["Dremel", "BMC Chisel", "Airbrush"],
    techniques: ["Diorama", "Battle Damage", "Scribing"],
    saveCount: 134, likeCount: 118, weeklyLikeCount: 56, createdAt: "2026-05-12T13:00:00Z",
  },
  {
    id: "12", title: "HG Kämpfer — Urban Combat Weathering",
    description: "Kämpfer weathered for urban warfare with soot, scrapes, and bullet impacts. Chain mine gimmick fully operational with custom base.",
    thumbnailUrl: getImage("Gunpla", 2),
    images: [
      lp("Gunpla", 2, "Action pose with diorama base"),
      lp("Gunpla", 3, "Soot and chipping detail"),
      lp("Gunpla", 4, "Shotgun closeup"),
    ],
    author: authors.a4, category: "Gunpla", tags: ["Weathering", "Battle Damage"],
    kit: "HG MS-18E Kämpfer", paints: ["Tamiya Dark Blue", "AK Interactive Soot", "Vallejo Silver"],
    tools: ["Sponge Chipping", "Airbrush", "Pigment Set"],
    techniques: ["Weathering", "Chipping", "Oil Wash"],
    saveCount: 112, likeCount: 99, weeklyLikeCount: 102, createdAt: "2026-05-28T08:00:00Z",
  },
  {
    id: "13", title: "Tiger I Ausf.E — Kursk 1943 Battle Scene",
    description: "1/35 Tiger I depicting the Battle of Kursk. Full zimmerit coating, mud effects, and spare track links.",
    thumbnailUrl: getImage("Military", 0),
    images: [
      lp("Military", 0, "Diorama front view"),
      lp("Military", 1, "Zimmerit texture detail"),
      lp("Military", 2, "Mud and track"),
      lp("Military", 3, "Commander hatch"),
    ],
    author: authors.a6, category: "Military", tags: ["Weathering", "Diorama"],
    kit: "Tamiya 1/35 Tiger I (Early)", paints: ["Tamiya XF-60 Dark Yellow", "AK Interactive Mud", "Vallejo Panzer Aces"],
    tools: ["Airbrush", "Hair Dryer", "Tamiya Putty"],
    techniques: ["Zimmerit", "Mud Effects", "Chipping"],
    saveCount: 287, likeCount: 264, weeklyLikeCount: 88, createdAt: "2026-05-08T10:00:00Z",
  },
  {
    id: "14", title: "Panzer IV Ausf.H — Eastern Front Winter",
    description: "Panzer IV in winter whitewash camouflage. Extensive stowage scratch-built, crew figures painted with oils.",
    thumbnailUrl: getImage("Military", 1),
    images: [
      lp("Military", 1, "Full side view"),
      lp("Military", 2, "Whitewash chipping"),
      lp("Military", 3, "Stowage detail"),
    ],
    author: authors.a6, category: "Military", tags: ["Weathering"],
    kit: "Tamiya 1/35 Panzer IV H", paints: ["Tamiya XF-2 White", "AK Interactive Winter Wash", "Vallejo Model Air"],
    tools: ["Sponge", "Airbrush", "Oil Brushes"],
    techniques: ["Whitewash", "Chipping", "Oil Wash"],
    saveCount: 198, likeCount: 181, weeklyLikeCount: 72, createdAt: "2026-04-18T09:00:00Z",
  },
  {
    id: "15", title: "M4 Sherman — Normandy Diorama",
    description: "M4 Sherman in a Normandy hedgerow diorama. Realistic foliage, hand-sculpted earth, and two resin figures.",
    thumbnailUrl: getImage("Military", 2),
    images: [
      lp("Military", 2, "Diorama overview"),
      lp("Military", 3, "Foliage and figures"),
      lp("Military", 4, "Hull weathering"),
    ],
    author: authors.a4, category: "Military", tags: ["Diorama", "Weathering"],
    kit: "Dragon 1/35 M4A1 Sherman", paints: ["Tamiya Olive Drab", "AK Interactive Earth", "Mig Ammo Streaks"],
    tools: ["Airbrush", "Sculpting Tools", "Natural Foliage"],
    techniques: ["Diorama", "Figure Painting", "Vegetation"],
    saveCount: 156, likeCount: 144, weeklyLikeCount: 61, createdAt: "2026-04-25T14:00:00Z",
  },
  {
    id: "16", title: "F-14A Tomcat — VF-84 Jolly Rogers NMF",
    description: "1/48 F-14A in natural metal finish for VF-84 Jolly Rogers. Alclad II NMF over polished Alclad primer.",
    thumbnailUrl: getImage("Military", 3),
    images: [
      lp("Military", 3, "3/4 top view"),
      lp("Military", 4, "NMF panel variation"),
      lp("Military", 0, "Cockpit detail"),
      lp("Military", 1, "Skull insignia"),
    ],
    author: authors.a7, category: "Military", tags: ["Scribing"],
    kit: "Tamiya 1/48 F-14A Tomcat", paints: ["Alclad NMF", "Alclad Polished Aluminum", "Tamiya Insignia White"],
    tools: ["Airbrush", "BMC Chisel", "Mr.Mark Setter"],
    techniques: ["NMF", "Scribing", "Decaling"],
    saveCount: 234, likeCount: 218, weeklyLikeCount: 95, createdAt: "2026-05-05T11:00:00Z",
  },
  {
    id: "17", title: "Spitfire Mk.IXc — Battle of Britain",
    description: "1/48 Spitfire in Battle of Britain markings. RAF camouflage with pre-shading and subtle weathering on poseable stand.",
    thumbnailUrl: getImage("Military", 4),
    images: [
      lp("Military", 4, "Top view — camo pattern"),
      lp("Military", 0, "Side profile"),
      lp("Military", 1, "Engine cowling"),
    ],
    author: authors.a7, category: "Military", tags: ["Weathering"],
    kit: "Tamiya 1/48 Spitfire Mk.IXc", paints: ["Tamiya Dark Green", "Tamiya Ocean Grey", "Tamiya Sky"],
    tools: ["Airbrush", "Fine Brush", "Masking Tape"],
    techniques: ["Pre-shading", "RAF Camo", "Panel Lining"],
    saveCount: 178, likeCount: 162, weeklyLikeCount: 79, createdAt: "2026-04-10T09:00:00Z",
  },
  {
    id: "18", title: "Ferrari 250 GTO — Rosso Corsa 1/24",
    description: "Tamiya's legendary 250 GTO in full Rosso Corsa livery. PE parts throughout and full engine detail with photo-etch.",
    thumbnailUrl: getImage("Car", 0),
    images: [
      lp("Car", 0, "3/4 front"),
      lp("Car", 1, "Engine bay open"),
      lp("Car", 2, "Interior detail"),
      lp("Car", 3, "Rear diffuser"),
    ],
    author: authors.a8, category: "Car", tags: ["Scribing"],
    kit: "Tamiya 1/24 Ferrari 250 GTO", paints: ["Mr.Color Italian Red", "Alclad Chrome", "Tamiya Clear"],
    tools: ["PE Bending Tool", "Airbrush", "Fine Brush"],
    techniques: ["PE Detailing", "Gloss Finish", "Engine Bay Detail"],
    saveCount: 145, likeCount: 134, weeklyLikeCount: 67, createdAt: "2026-05-02T10:00:00Z",
  },
  {
    id: "19", title: "IJN Yamato 1/350 — Final Sortie Diorama",
    description: "1/350 Yamato with full rigging, crew figures, and dynamic ocean base depicting the final sortie in April 1945.",
    thumbnailUrl: getImage("Diorama", 3),
    images: [
      lp("Diorama", 3, "Full broadside"),
      lp("Diorama", 4, "Bow view — ocean base"),
      lp("Diorama", 0, "Bridge and AA guns"),
      lp("Diorama", 1, "Stern rigging"),
    ],
    author: authors.a5, category: "Diorama", tags: ["Diorama", "Weathering"],
    kit: "Tamiya 1/350 IJN Yamato", paints: ["Mr.Color Ship Hull Red", "Tamiya Dark Sea Gray", "Alclad Steel"],
    tools: ["Rigging Thread", "Photo-etch Set", "Airbrush"],
    techniques: ["Rigging", "Ocean Base", "Figure Painting"],
    saveCount: 312, likeCount: 298, weeklyLikeCount: 83, createdAt: "2026-04-05T08:00:00Z",
  },
];

export const tags: Tag[] = [
  { id: "t1", label: "Weathering",    labelJa: "ウェザリング",     count: 9 },
  { id: "t2", label: "Candy Paint",   labelJa: "キャンディ塗装",   count: 3 },
  { id: "t3", label: "LED",           labelJa: "LED組み込み",      count: 4 },
  { id: "t4", label: "Scribing",      labelJa: "スジ彫り",         count: 6 },
  { id: "t5", label: "Diorama",       labelJa: "ジオラマ",         count: 7 },
  { id: "t6", label: "Battle Damage", labelJa: "バトルダメージ",   count: 5 },
];
